### ISSUE TITLE
Some models don't have the published column yet.

### ISSUE THREAD

**Issue by trtstm** [micado-eu/backend#22]
The following models do not have a published column yet: FeaturesFlags, PictureHotspot, Step, StepLink.
This is needed so that the translated strings will be pushed to the prod table.

**Comment by GiuseppeCSI** [comment]
I'm not sure about FeatureFlags, but for the other entities the columns are not there because those entities are dependent on others. For example, steps cannot exits without a process, so we tought it would cumbersome having to first publish the process and then publish every single step. So, right now, publishing the process means also publishing all associated steps.
If needed, we can readd the published column to these entities and add some more logic to manage the switch to published

**Comment by gioppoluca** [comment]
All the mentioned tables DO NOT NEED a published column since they are linked to a master table that degermine IF that entity is published or not.
In specific:
- feature flags will never go to the weblate since is used only in the PA application and we will translate it only in main EU languages.
- all others are dependant, as @GiuseppeCSI  was explaining, to another table, when that row of the main table is published also the referred elements do.
