### ISSUE TITLE
State Machin Diagram for translations

### ISSUE THREAD

**Issue by GiuseppeCSI** [micado-eu/backend#5]
This is the state machine diagram for translations 
![image](https://user-images.githubusercontent.com/59613800/92603947-32e11880-f2b0-11ea-88fe-24b41138b919.png)

**Comment by mthsbk** [comment]
I tried it out in Weblate and this should be possible.
Whenever it is translatable, we add it to the JSON file of the source language. Once it was translated, we remove it again from Weblate.

We just need to make sure to also remove it in the translation json, because otherwise Weblate will just 'remember' the previous translation and not denote it as a string that needs translations.

So this gives us a new situation that we need to look at. What if we created a giant wall of text, send it to the translators, they translated it. Now the editor changes one word in the original language. How can we tell weblate that the translations need to be updated without needing to write from scratch again?

Apart from that I don't see any technical constraints with this approach.

cc @gioppoluca @webdevotion @janblonde

**Comment by gioppoluca** [comment]
I vote against "removing" from weblate after translation

We have GITEA for keeping thing correctly updated

Once we push the new original in GITEA weblate will know since it uses webhooks and mark the pieces new as such, but we need to test the whole things.  We need to talk on this

**Comment by mthsbk** [comment]
By removing from Weblate I meant removing in Git which propagates to Weblate.

**Comment by trtstm** [comment]
Do these states correspond with the translationState field in the models? If so are they just assigned 1,2,3 etc from left to right?
